name = "Aglaus"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_aglaus/blob/master/LICENSE.md"
description = "Aglaus is list design with eyecatch theme.Inspired by lanyon."
homepage = "http://yet.unresolved.xyz/hugo_theme_aglaus"
tags = ["blog", "list", "eyecatch"]
features = ["blog"]

[author]
    name = "Daisuke Tsuji"
    homepage = "http://yet.unresolved.xyz"

